print('Enter the first number')
firstNumber = int(input())
print('Enter the Second number')
secondNumber = int(input())
sum = int(firstNumber)+ int(secondNumber)
print('The sum of two mumber ' + str(int(sum)))
